import React, { useState, useEffect } from "react";
import { MEDICAL_SPECIALTIES } from "../data";
import { MCQ, DrugProfile } from "../types";
import { Users, FileText, DollarSign, PlusCircle, CheckCircle, UploadCloud, PieChart, Activity, TrendingUp, Cpu, RefreshCw } from "lucide-react";

interface AdminFacultyPanelProps {
  onAddCustomMCQ: (mcq: MCQ) => void;
  onAddCustomDrug: (drug: DrugProfile) => void;
}

export default function AdminFacultyPanel({ onAddCustomMCQ, onAddCustomDrug }: AdminFacultyPanelProps) {
  const [activeSubTab, setActiveSubTab] = useState<"metrics" | "add-mcq" | "add-drug">("metrics");
  const [metrics, setMetrics] = useState<{
    activeStudents: number;
    monthlyMRR: string;
    licensedUniversities: number;
    aiEngineCalls: string;
    customMCQs: number;
    customDrugs: number;
  } | null>(null);
  const [metricsLoading, setMetricsLoading] = useState(true);

  useEffect(() => {
    setMetricsLoading(true);
    fetch("/api/platform-metrics")
      .then(res => res.json())
      .then(data => {
        setMetrics(data);
        setMetricsLoading(false);
      })
      .catch(() => setMetricsLoading(false));
  }, []);

  // Custom MCQ Form State
  const [mcqQuestion, setMcqQuestion] = useState("");
  const [mcqOptions, setMcqOptions] = useState(["", "", "", ""]);
  const [mcqCorrect, setMcqCorrect] = useState(0);
  const [mcqRationale, setMcqRationale] = useState("");
  const [mcqSpecialty, setMcqSpecialty] = useState("Cardiology");
  const [mcqDifficulty, setMcqDifficulty] = useState<"Easy" | "Medium" | "Hard">("Medium");
  const [mcqSuccessMessage, setMcqSuccessMessage] = useState("");

  // Custom Drug Form State
  const [drugGeneric, setDrugGeneric] = useState("");
  const [drugBrand, setDrugBrand] = useState("");
  const [drugClass, setDrugClass] = useState("");
  const [drugIndications, setDrugIndications] = useState("");
  const [drugContraindications, setDrugContraindications] = useState("");
  const [drugDosage, setDrugDosage] = useState("");
  const [drugManufacturer, setDrugManufacturer] = useState("");
  const [drugSuccessMessage, setDrugSuccessMessage] = useState("");

  // Handler to Submit MCQ
  const handleMCQSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!mcqQuestion.trim() || mcqOptions.some(opt => !opt.trim())) return;

    const newMCQ: MCQ = {
      question: mcqQuestion,
      options: mcqOptions,
      correctAnswer: mcqCorrect,
      rationale: mcqRationale || "Rationale is currently being generated by Faculty.",
      difficulty: mcqDifficulty,
      specialty: mcqSpecialty
    };

    onAddCustomMCQ(newMCQ);
    setMcqQuestion("");
    setMcqOptions(["", "", "", ""]);
    setMcqCorrect(0);
    setMcqRationale("");
    setMcqSuccessMessage("Success: custom MCQ added to Q-Bank registry! Verified by MedGlobal Academic Board.");
    setTimeout(() => setMcqSuccessMessage(""), 4000);
  };

  // Handler to Submit Drug
  const handleDrugSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!drugGeneric.trim() || !drugBrand.trim() || !drugClass.trim()) return;

    const newDrug: DrugProfile = {
      genericName: drugGeneric,
      brandName: drugBrand,
      manufacturer: drugManufacturer || "MedGlobal Pharma Partners",
      drugClass: drugClass,
      indications: drugIndications || "Clinical indications specified by FDA research team.",
      contraindications: drugContraindications || "Contraindications pending review.",
      sideEffects: "Gastrointestinal disturbances, headaches.",
      drugInteractions: "Diuretics.",
      dosage: drugDosage || "As directed by physician.",
      pregnancyCategory: "Category B",
      lactationSafety: "Compatible with caution.",
      fdaStatus: "Approved"
    };

    onAddCustomDrug(newDrug);
    setDrugGeneric("");
    setDrugBrand("");
    setDrugClass("");
    setDrugIndications("");
    setDrugContraindications("");
    setDrugDosage("");
    setDrugManufacturer("");
    setDrugSuccessMessage("Success: custom pharmaceutical profile registered! Added to live drug database.");
    setTimeout(() => setDrugSuccessMessage(""), 4000);
  };

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-[#E2E8F0] overflow-hidden" id="admin-faculty-dashboard">
      {/* Sub Tabs */}
      <div className="bg-[#FCFCFD] border-b border-[#E2E8F0] p-3 flex gap-2 flex-wrap" id="admin-subtabs">
        <button
          onClick={() => setActiveSubTab("metrics")}
          className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-lg transition-all flex items-center gap-1.5 ${activeSubTab === "metrics" ? "bg-[#003B95] text-white font-serif italic" : "text-[#64748B] hover:bg-slate-100"}`}
        >
          <TrendingUp className="h-3.5 w-3.5" />
          <span>Platform Metrics</span>
        </button>
        <button
          onClick={() => setActiveSubTab("add-mcq")}
          className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-lg transition-all flex items-center gap-1.5 ${activeSubTab === "add-mcq" ? "bg-[#003B95] text-white font-serif italic" : "text-[#64748B] hover:bg-slate-100"}`}
        >
          <PlusCircle className="h-3.5 w-3.5" />
          <span>Faculty MCQ Editor</span>
        </button>
        <button
          onClick={() => setActiveSubTab("add-drug")}
          className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-lg transition-all flex items-center gap-1.5 ${activeSubTab === "add-drug" ? "bg-[#003B95] text-white font-serif italic" : "text-[#64748B] hover:bg-slate-100"}`}
        >
          <PlusCircle className="h-3.5 w-3.5" />
          <span>Drug Database Editor</span>
        </button>
      </div>

      {/* METRICS VIEW */}
      {activeSubTab === "metrics" && (
        <div className="p-4 md:p-6 space-y-6 bg-white">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="bg-white border border-[#E2E8F0] p-4 rounded-xl flex items-center gap-3.5 shadow-sm">
              <div className="p-2.5 rounded-full bg-[#003B95]/10 text-[#003B95]">
                <Users className="h-5 w-5" />
              </div>
              <div>
                <div className="text-[9px] text-[#64748B] font-extrabold uppercase tracking-wider">Active Students</div>
                {metricsLoading ? (
                  <div className="h-5 w-20 bg-slate-200 animate-pulse rounded mt-1" />
                ) : (
                  <div className="text-xl font-extrabold text-[#0F172A] font-serif">{(metrics?.activeStudents ?? 142508).toLocaleString()}</div>
                )}
              </div>
            </div>
            <div className="bg-white border border-[#E2E8F0] p-4 rounded-xl flex items-center gap-3.5 shadow-sm">
              <div className="p-2.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-100">
                <DollarSign className="h-5 w-5" />
              </div>
              <div>
                <div className="text-[9px] text-[#64748B] font-extrabold uppercase tracking-wider">Monthly MRR</div>
                {metricsLoading ? (
                  <div className="h-5 w-20 bg-slate-200 animate-pulse rounded mt-1" />
                ) : (
                  <div className="text-xl font-extrabold text-[#0F172A] font-serif">{metrics?.monthlyMRR ?? "$64,280"}</div>
                )}
              </div>
            </div>
            <div className="bg-white border border-[#E2E8F0] p-4 rounded-xl flex items-center gap-3.5 shadow-sm">
              <div className="p-2.5 rounded-full bg-[#003B95]/10 text-[#003B95]">
                <FileText className="h-5 w-5" />
              </div>
              <div>
                <div className="text-[9px] text-[#64748B] font-extrabold uppercase tracking-wider">Licensed Universities</div>
                {metricsLoading ? (
                  <div className="h-5 w-20 bg-slate-200 animate-pulse rounded mt-1" />
                ) : (
                  <div className="text-xl font-bold text-[#0F172A] font-serif">{metrics?.licensedUniversities ?? 48} Partner Colleges</div>
                )}
              </div>
            </div>
            <div className="bg-white border border-[#E2E8F0] p-4 rounded-xl flex items-center gap-3.5 shadow-sm">
              <div className="p-2.5 rounded-full bg-[#003B95]/10 text-[#003B95]">
                <Cpu className="h-5 w-5 animate-pulse" />
              </div>
              <div>
                <div className="text-[9px] text-[#64748B] font-extrabold uppercase tracking-wider">AI Engines Calls</div>
                {metricsLoading ? (
                  <div className="h-5 w-20 bg-slate-200 animate-pulse rounded mt-1" />
                ) : (
                  <div className="text-xl font-bold text-[#0F172A] font-serif">{metrics?.aiEngineCalls ?? "1.2 Million / Mo"}</div>
                )}
              </div>
            </div>
          </div>

          {/* Live Q-Bank content stats */}
          {metrics && (metrics.customMCQs > 0 || metrics.customDrugs > 0) && (
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-blue-50 border border-blue-100 p-4 rounded-xl flex items-center gap-3">
                <PlusCircle className="h-5 w-5 text-[#003B95]" />
                <div>
                  <div className="text-[9px] text-[#64748B] font-extrabold uppercase tracking-wider">Faculty MCQs Published</div>
                  <div className="text-xl font-extrabold text-[#003B95] font-serif">{metrics.customMCQs}</div>
                </div>
              </div>
              <div className="bg-emerald-50 border border-emerald-100 p-4 rounded-xl flex items-center gap-3">
                <Activity className="h-5 w-5 text-emerald-700" />
                <div>
                  <div className="text-[9px] text-[#64748B] font-extrabold uppercase tracking-wider">Drugs Registered</div>
                  <div className="text-xl font-extrabold text-emerald-700 font-serif">{metrics.customDrugs}</div>
                </div>
              </div>
            </div>
          )}

          {/* Users List & Lectures Log */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="border border-[#E2E8F0] rounded-xl p-4 space-y-3 bg-white">
              <h4 className="text-[10px] font-extrabold text-[#64748B] uppercase tracking-widest">Recent Registered Students</h4>
              <div className="space-y-2 text-xs">
                <div className="flex justify-between p-3 bg-[#FCFCFD] border border-[#E2E8F0] rounded-lg">
                  <div>
                    <span className="font-bold text-slate-800 font-serif">Dr. Sarah Vance</span>
                    <p className="text-[10px] text-gray-400">FCPS Trainee • Cardiology</p>
                  </div>
                  <span className="text-teal-600 font-extrabold text-[10px] uppercase tracking-wider mt-1">Pass Standard</span>
                </div>
                <div className="flex justify-between p-3 bg-[#FCFCFD] border border-[#E2E8F0] rounded-lg">
                  <div>
                    <span className="font-bold text-slate-800 font-serif">Alexandre Mercer</span>
                    <p className="text-[10px] text-gray-400">MBBS Year 4 Student</p>
                  </div>
                  <span className="text-[#003B95] font-extrabold text-[10px] uppercase tracking-wider mt-1">In-Progress</span>
                </div>
                <div className="flex justify-between p-3 bg-[#FCFCFD] border border-[#E2E8F0] rounded-lg">
                  <div>
                    <span className="font-bold text-slate-800 font-serif">Prof. Marcus Sterling</span>
                    <p className="text-[10px] text-gray-400">Faculty Dean • Pathology</p>
                  </div>
                  <span className="text-[#003B95] font-extrabold text-[10px] uppercase tracking-wider mt-1">Supervisor</span>
                </div>
              </div>
            </div>

            <div className="border border-[#E2E8F0] rounded-xl p-4 space-y-3 bg-white">
              <h4 className="text-[10px] font-extrabold text-[#64748B] uppercase tracking-widest">Lecture Upload Logs & Workshops</h4>
              <div className="space-y-2.5">
                <div className="flex items-center gap-2 p-3 bg-[#FCFCFD] border border-[#E2E8F0] rounded-lg text-xs">
                  <UploadCloud className="h-4 w-4 text-[#003B95]" />
                  <div className="flex-1">
                    <span className="font-bold block text-slate-800">Hyperkalemia Treatment Algorithm.pdf</span>
                    <span className="text-[10px] text-gray-400">Uploaded by Dr. Sterling • Today</span>
                  </div>
                  <span className="bg-emerald-50 text-emerald-800 font-bold text-[9px] px-1.5 py-0.5 rounded uppercase border border-emerald-100">Live</span>
                </div>
                <div className="flex items-center gap-2 p-3 bg-[#FCFCFD] border border-[#E2E8F0] rounded-lg text-xs">
                  <UploadCloud className="h-4 w-4 text-[#003B95]" />
                  <div className="flex-1">
                    <span className="font-bold block text-slate-800">Meta-Analysis Cochrane Risk Bias Setup.mp4</span>
                    <span className="text-[10px] text-gray-400">Uploaded by Biostat Department • 2 Days ago</span>
                  </div>
                  <span className="bg-emerald-50 text-emerald-800 font-bold text-[9px] px-1.5 py-0.5 rounded uppercase border border-emerald-100">Live</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* FACULTY MCQ CREATOR */}
      {activeSubTab === "add-mcq" && (
        <form onSubmit={handleMCQSubmit} className="p-5 md:p-6 space-y-4 bg-white">
          <div className="flex justify-between items-center border-b border-[#E2E8F0] pb-3">
            <h3 className="font-serif italic font-bold text-[#0F172A] text-lg">Write & Publish MCQ Questions</h3>
            <span className="text-xs text-gray-400">Direct integration to student assessment module</span>
          </div>

          {mcqSuccessMessage && (
            <div className="p-3 bg-green-50 border border-green-200 text-green-800 rounded-xl text-xs flex items-center gap-1.5 font-semibold">
              <CheckCircle className="h-4 w-4" />
              <span>{mcqSuccessMessage}</span>
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
            <div className="md:col-span-8">
              <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Clinical Vignette / Question Body</label>
              <textarea
                value={mcqQuestion}
                onChange={(e) => setMcqQuestion(e.target.value)}
                placeholder="A 45-year-old male presents with severe chest pain... What is the next best diagnostic step?"
                rows={4}
                required
                className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs md:text-sm p-3 rounded-xl outline-none focus:border-[#003B95] focus:bg-white transition-all resize-none"
              />
            </div>
            <div className="md:col-span-4 space-y-3">
              <div>
                <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Medical Department</label>
                <select
                  value={mcqSpecialty}
                  onChange={(e) => setMcqSpecialty(e.target.value)}
                  className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs py-2.5 px-3 rounded-lg text-slate-800 outline-none focus:border-[#003B95]"
                >
                  {MEDICAL_SPECIALTIES.map(sp => (
                    <option key={sp.id} value={sp.name}>{sp.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Target Difficulty</label>
                <select
                  value={mcqDifficulty}
                  onChange={(e) => setMcqDifficulty(e.target.value as any)}
                  className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs py-2.5 px-3 rounded-lg text-slate-800 outline-none focus:border-[#003B95]"
                >
                  <option value="Easy">Easy</option>
                  <option value="Medium">Medium</option>
                  <option value="Hard">Hard</option>
                </select>
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B]">Question Choices</label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {mcqOptions.map((opt, idx) => (
                <div key={idx} className="flex items-center gap-2">
                  <span className="w-6 h-6 rounded-full bg-[#003B95]/10 text-[#003B95] flex items-center justify-center text-xs font-bold shrink-0">{String.fromCharCode(65 + idx)}</span>
                  <input
                    type="text"
                    value={opt}
                    onChange={(e) => {
                      const copy = [...mcqOptions];
                      copy[idx] = e.target.value;
                      setMcqOptions(copy);
                    }}
                    placeholder={`Option ${String.fromCharCode(65 + idx)}`}
                    required
                    className="flex-1 bg-[#FCFCFD] border border-[#E2E8F0] py-2 px-3 text-xs rounded-lg outline-none focus:border-[#003B95] focus:bg-white"
                  />
                  <input
                    type="radio"
                    name="correct-answer"
                    checked={mcqCorrect === idx}
                    onChange={() => setMcqCorrect(idx)}
                    className="h-4 w-4 accent-[#003B95] cursor-pointer"
                    title="Mark as correct answer"
                  />
                </div>
              ))}
            </div>
          </div>

          <div>
            <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Pathophysiological Rationale & Explanations</label>
            <textarea
              value={mcqRationale}
              onChange={(e) => setMcqRationale(e.target.value)}
              placeholder="Explain why the marked option is correct and why other options are distraction parameters..."
              rows={2}
              className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs p-3 rounded-xl outline-none focus:border-[#003B95] focus:bg-white"
            />
          </div>

          <button
            type="submit"
            className="bg-[#003B95] hover:bg-blue-950 text-white font-extrabold text-[10px] uppercase tracking-wider py-3 px-6 rounded-lg transition-all"
            id="btn-publish-mcq"
          >
            Approve & Publish Question
          </button>
        </form>
      )}

      {/* DRUG REGISTRY EDITOR */}
      {activeSubTab === "add-drug" && (
        <form onSubmit={handleDrugSubmit} className="p-5 md:p-6 space-y-4 bg-white">
          <div className="flex justify-between items-center border-b border-[#E2E8F0] pb-3">
            <h3 className="font-serif italic font-bold text-[#0F172A] text-lg">Register New Pharmaceutical Compound</h3>
            <span className="text-xs text-gray-400">Publish guidelines to Medical Drug Center</span>
          </div>

          {drugSuccessMessage && (
            <div className="p-3 bg-green-50 border border-green-200 text-green-800 rounded-xl text-xs flex items-center gap-1.5 font-semibold">
              <CheckCircle className="h-4 w-4" />
              <span>{drugSuccessMessage}</span>
            </div>
          )}

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Generic Scientific Name</label>
              <input
                type="text"
                value={drugGeneric}
                onChange={(e) => setDrugGeneric(e.target.value)}
                placeholder="e.g. 'Atorvastatin Calcium'"
                required
                className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs py-2.5 px-3 rounded-lg outline-none focus:border-[#003B95] focus:bg-white"
              />
            </div>
            <div>
              <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Common Brand Name</label>
              <input
                type="text"
                value={drugBrand}
                onChange={(e) => setDrugBrand(e.target.value)}
                placeholder="e.g. 'Lipitor'"
                required
                className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs py-2.5 px-3 rounded-lg outline-none focus:border-[#003B95] focus:bg-white"
              />
            </div>
            <div>
              <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Pharmacological Class</label>
              <input
                type="text"
                value={drugClass}
                onChange={(e) => setDrugClass(e.target.value)}
                placeholder="e.g. 'HMG-CoA Reductase Inhibitor'"
                required
                className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs py-2.5 px-3 rounded-lg outline-none focus:border-[#003B95] focus:bg-white"
              />
            </div>
            <div>
              <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Key Manufacturer</label>
              <input
                type="text"
                value={drugManufacturer}
                onChange={(e) => setDrugManufacturer(e.target.value)}
                placeholder="e.g. 'Pfizer / Viatris'"
                className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs py-2.5 px-3 rounded-lg outline-none focus:border-[#003B95] focus:bg-white"
              />
            </div>
          </div>

          <div>
            <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Clinical Indications</label>
            <textarea
              value={drugIndications}
              onChange={(e) => setDrugIndications(e.target.value)}
              placeholder="e.g. 'Hypercholesterolemia management, prevention of coronary events...'"
              rows={2}
              className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs p-3 rounded-lg outline-none focus:border-[#003B95] focus:bg-white"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Absolute Contraindications</label>
              <input
                type="text"
                value={drugContraindications}
                onChange={(e) => setDrugContraindications(e.target.value)}
                placeholder="e.g. 'Active hepatic disease...'"
                className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs py-2.5 px-3 rounded-lg outline-none focus:border-[#003B95] focus:bg-white"
              />
            </div>
            <div>
              <label className="block text-[10px] font-extrabold uppercase tracking-widest text-[#64748B] mb-1">Adult Dosage Guidelines</label>
              <input
                type="text"
                value={drugDosage}
                onChange={(e) => setDrugDosage(e.target.value)}
                placeholder="e.g. '10 mg to 80 mg orally once daily...'"
                className="w-full bg-[#FCFCFD] border border-[#E2E8F0] text-xs py-2.5 px-3 rounded-lg outline-none focus:border-[#003B95] focus:bg-white"
              />
            </div>
          </div>

          <button
            type="submit"
            className="bg-[#003B95] hover:bg-blue-950 text-white font-extrabold text-[10px] uppercase tracking-wider py-3 px-6 rounded-lg transition-all"
            id="btn-publish-drug"
          >
            Register Compound Profile
          </button>
        </form>
      )}
    </div>
  );
}
